import type { MenuCategory, MenuItem } from "@/types"

export const menuCategories: MenuCategory[] = [
  { id: "featured", name: "In Evidenza", order: 0 },
  { id: "burgers", name: "Burgers", description: "Tutti i burger sono serviti con patatine e bibita", order: 1 },
  { id: "wraps", name: "Wraps", description: "Tutti i wrap sono serviti con patatine e bibita", order: 2 },
  { id: "tacos", name: "French Tacos", description: "Tacos alla francese con patatine e bibita", order: 3 },
  { id: "chicken", name: "Chicken Menu", description: "Piatti di pollo", order: 4 },
  { id: "insalate", name: "Insalate", order: 5 },
  {
    id: "indpak",
    name: "Ind/Pak Menu",
    description: "Naan, Curry, Biryani, Korma, Tikka Masala e altri piatti indiani e pakistani",
    order: 6,
  },
  { id: "naan", name: "Naan", description: "Pane naan tradizionale", order: 7 },
  { id: "curries", name: "Curries", description: "Curry tradizionali", order: 8 },
  { id: "tandoori", name: "Tandoori Grill", description: "Specialità alla griglia tandoori", order: 9 },
  { id: "rice", name: "Rice", description: "Riso e biryani", order: 10 },
  { id: "snacks", name: "Snacks", order: 11 },
  { id: "family", name: "Family Deals", order: 12 },
  { id: "desserts", name: "Desserts", order: 13 },
  { id: "bevande", name: "Bevande", order: 14 },
]

export const menuItems: MenuItem[] = [
  // ============ FEATURED ============
  {
    id: "featured-doppio-hamburger",
    categoryId: "featured",
    name: "Doppio Hamburger",
    description: "Double beef patty with special curry sauce, lettuce, tomato, and cheese",
    priceEur: 11.5,
    imageUrl: "/double-burger-with-curry-sauce--professional-food-.jpg",
    available: true,
    published: true,
  },
  {
    id: "featured-tikka-burger",
    categoryId: "featured",
    name: "Tikka Burger",
    description: "Grilled chicken tikka with mint chutney, onions, and fresh vegetables",
    priceEur: 9.99,
    imageUrl: "/tikka-chicken-burger--professional-food-photograph.jpg",
    available: true,
    published: true,
  },
  {
    id: "featured-chicken-nuggets",
    categoryId: "featured",
    name: "Chicken Nuggets 6pz",
    description: "Crispy golden nuggets with your choice of dipping sauce",
    priceEur: 6.5,
    imageUrl: "/crispy-chicken-nuggets--professional-food-photogra.jpg",
    available: true,
    published: true,
  },
  {
    id: "featured-family-deal",
    categoryId: "featured",
    name: "Family Burger Deal",
    description: "4 burgers, 4 drinks, large fries - perfect for the family",
    priceEur: 39.99,
    imageUrl: "/family-burger-meal-deal--professional-food-photogr.jpg",
    available: true,
    published: true,
  },

  // ============ BURGERS ============
  {
    id: "hamburger",
    categoryId: "burgers",
    name: "Hamburger",
    description: "Classic beef patty burger with fresh vegetables and special sauce",
    priceEur: 8.5,
    imageUrl: "/classic-hamburger.jpg",
    available: true,
    published: true,
  },
  {
    id: "doppio-hamburger",
    categoryId: "burgers",
    name: "Doppio Hamburger",
    description: "Double beef patty with special curry sauce, lettuce, tomato, and cheese",
    priceEur: 11.5,
    imageUrl: "/double-burger-with-curry-sauce--professional-food-.jpg",
    available: true,
    published: true,
  },
  {
    id: "tikka-burger",
    categoryId: "burgers",
    name: "Tikka Burger",
    description: "Grilled chicken tikka with mint chutney, onions, and fresh vegetables",
    priceEur: 9.99,
    imageUrl: "/tikka-chicken-burger--professional-food-photograph.jpg",
    available: true,
    published: true,
  },
  {
    id: "chicken-royal",
    categoryId: "burgers",
    name: "Chicken Royal",
    description: "Crispy chicken fillet with royal sauce, lettuce, and pickles",
    priceEur: 11.5,
    imageUrl: "/chicken-royal-burger.jpg",
    available: true,
    published: true,
  },
  {
    id: "chicken-special",
    categoryId: "burgers",
    name: "Chicken Special",
    description: "Special grilled chicken burger with secret sauce and fresh vegetables",
    priceEur: 10.99,
    imageUrl: "/chicken-special-burger.jpg",
    available: true,
    published: true,
  },
  {
    id: "mega-tikka-parmigiano",
    categoryId: "burgers",
    name: "Mega Tikka Parmigiano",
    description: "Giant tikka chicken burger with melted parmigiano cheese",
    priceEur: 13.99,
    imageUrl: "/mega-tikka-parmigiano-burger.jpg",
    available: true,
    published: true,
  },
  {
    id: "mega-beef-parmigiano",
    categoryId: "burgers",
    name: "Mega Beef Parmigiano",
    description: "Giant beef burger with melted parmigiano cheese",
    priceEur: 14.5,
    imageUrl: "/mega-beef-parmigiano-burger.jpg",
    available: true,
    published: true,
  },
  {
    id: "mega-chicken-parmigiano",
    categoryId: "burgers",
    name: "Mega Chicken Parmigiano",
    description: "Giant crispy chicken burger with melted parmigiano cheese",
    priceEur: 13.99,
    imageUrl: "/mega-chicken-parmigiano-burger.jpg",
    available: true,
    published: true,
  },
  {
    id: "mega-fried-parmigiano",
    categoryId: "burgers",
    name: "Mega Fried Parmigiano",
    description: "Giant fried chicken burger with melted parmigiano cheese",
    priceEur: 13.99,
    imageUrl: "/mega-fried-parmigiano-burger.jpg",
    available: true,
    published: true,
  },
  {
    id: "hot-dog",
    categoryId: "burgers",
    name: "Hot Dog",
    description: "Classic American hot dog with mustard and ketchup",
    priceEur: 6.5,
    imageUrl: "/classic-hot-dog.png",
    available: true,
    published: true,
  },
  {
    id: "black-diamond-pollo-grill",
    categoryId: "burgers",
    name: "Black Diamond Pollo Grill",
    description: "Premium grilled chicken burger with black diamond sauce",
    priceEur: 12.99,
    imageUrl: "/black-diamond-grilled-chicken-burger.jpg",
    available: true,
    published: true,
  },
  {
    id: "black-diamond-beef-burger",
    categoryId: "burgers",
    name: "Black Diamond Beef Burger",
    description: "Premium beef burger with black diamond sauce",
    priceEur: 13.5,
    imageUrl: "/black-diamond-beef-burger.jpg",
    available: true,
    published: true,
  },

  // ============ WRAPS ============
  {
    id: "wrap-pollo-grill",
    categoryId: "wraps",
    name: "Wrap Pollo Grill",
    description: "Grilled chicken wrap with fresh vegetables and special sauce",
    priceEur: 9.5,
    imageUrl: "/grilled-chicken-wrap.jpg",
    available: true,
    published: true,
  },
  {
    id: "wrap-pollo-fritto",
    categoryId: "wraps",
    name: "Wrap Pollo Fritto",
    description: "Crispy fried chicken wrap with fresh vegetables",
    priceEur: 9.5,
    imageUrl: "/fried-chicken-wrap.jpg",
    available: true,
    published: true,
  },
  {
    id: "chicken-tikka-wrap",
    categoryId: "wraps",
    name: "Chicken Tikka Wrap",
    description: "Chicken tikka wrap with mint chutney and fresh vegetables",
    priceEur: 9.99,
    imageUrl: "/chicken-tikka-wrap.jpg",
    available: true,
    published: true,
  },
  {
    id: "wrap-vegetariano",
    categoryId: "wraps",
    name: "Wrap Vegetariano",
    description: "Fresh vegetarian wrap with hummus and grilled vegetables",
    priceEur: 8.99,
    imageUrl: "/vegetarian-wrap.png",
    available: true,
    published: true,
  },

  // ============ TACOS ============
  {
    id: "tacos-pollo-fritto",
    categoryId: "tacos",
    name: "Tacos Pollo Fritto",
    description: "French tacos with crispy fried chicken, cheese sauce, and fries inside",
    priceEur: 9.99,
    imageUrl: "/french-tacos-fried-chicken.jpg",
    available: true,
    published: true,
  },
  {
    id: "tacos-pollo-grill",
    categoryId: "tacos",
    name: "Tacos Pollo Grill",
    description: "French tacos with grilled chicken, cheese sauce, and fries inside",
    priceEur: 9.99,
    imageUrl: "/french-tacos-grilled-chicken.jpg",
    available: true,
    published: true,
  },
  {
    id: "tacos-extra-spicy",
    categoryId: "tacos",
    name: "Tacos Extra Spicy",
    description: "Extra spicy french tacos with hot sauce and jalapeños",
    priceEur: 10.5,
    imageUrl: "/spicy-french-tacos.jpg",
    available: true,
    published: true,
    spicyLevel: 4,
  },
  {
    id: "tacos-vegetariano",
    categoryId: "tacos",
    name: "Tacos Vegetariano",
    description: "Vegetarian french tacos with grilled vegetables and cheese",
    priceEur: 8.99,
    imageUrl: "/vegetarian-french-tacos.jpg",
    available: true,
    published: true,
    isVegetarian: true,
  },

  // ============ CHICKEN MENU ============
  {
    id: "3x-chicken",
    categoryId: "chicken",
    name: "3 x Chicken",
    description: "3 pieces of crispy fried chicken",
    priceEur: 8.99,
    imageUrl: "/3-pieces-fried-chicken.jpg",
    available: true,
    published: true,
  },
  {
    id: "chicken-mix",
    categoryId: "chicken",
    name: "Chicken Mix",
    description: "Mixed chicken pieces - wings, drumsticks, and strips",
    priceEur: 12.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "alette-di-pollo",
    categoryId: "chicken",
    name: "Alette di Pollo",
    description: "Crispy chicken wings with your choice of sauce",
    priceEur: 7.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "strisce-di-pollo",
    categoryId: "chicken",
    name: "Strisce di Pollo",
    description: "Crispy chicken strips with dipping sauce",
    priceEur: 8.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "chicken-nuggets-6",
    categoryId: "chicken",
    name: "Chicken Nuggets 6pz",
    description: "6 crispy golden chicken nuggets",
    priceEur: 6.5,
    imageUrl: "/crispy-chicken-nuggets--professional-food-photogra.jpg",
    available: true,
    published: true,
  },
  {
    id: "chicken-nuggets-10",
    categoryId: "chicken",
    name: "Chicken Nuggets 10pz",
    description: "10 crispy golden chicken nuggets",
    priceEur: 9.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },

  // ============ INSALATE ============
  {
    id: "insalata-pollo-bianco-grill",
    categoryId: "insalate",
    name: "Insalata Pollo Bianco Grill",
    description: "Fresh salad with grilled white chicken breast",
    priceEur: 9.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "insalata-pollo-tikka",
    categoryId: "insalate",
    name: "Insalata Pollo Tikka",
    description: "Fresh salad with chicken tikka pieces",
    priceEur: 9.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "insalata-vegetariana",
    categoryId: "insalate",
    name: "Insalata Vegetariana",
    description: "Fresh mixed vegetarian salad",
    priceEur: 7.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "caesar-salad",
    categoryId: "insalate",
    name: "Caesar Salad",
    description: "Classic Caesar salad with parmesan and croutons",
    priceEur: 8.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },

  // ============ IND/PAK MENU ============
  {
    id: "chicken-biryani",
    categoryId: "indpak",
    name: "Chicken Biryani",
    description: "Aromatic basmati rice layered with spiced chicken",
    priceEur: 12.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "lamb-biryani",
    categoryId: "indpak",
    name: "Lamb Biryani",
    description: "Aromatic basmati rice layered with spiced lamb",
    priceEur: 14.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "vegetable-biryani",
    categoryId: "indpak",
    name: "Vegetable Biryani",
    description: "Aromatic basmati rice with mixed vegetables",
    priceEur: 10.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "rice-platter",
    categoryId: "indpak",
    name: "Rice Platter",
    description: "Rice served with curry of your choice",
    priceEur: 13.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "naan-plain",
    categoryId: "indpak",
    name: "Naan Plain",
    description: "Traditional plain naan bread",
    priceEur: 2.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "naan-butter",
    categoryId: "indpak",
    name: "Naan Butter",
    description: "Soft naan bread brushed with butter",
    priceEur: 3.0,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "naan-garlic",
    categoryId: "indpak",
    name: "Naan Garlic",
    description: "Naan bread with garlic and herbs",
    priceEur: 3.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "naan-cheese",
    categoryId: "indpak",
    name: "Naan Cheese",
    description: "Naan bread stuffed with melted cheese",
    priceEur: 4.0,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "naan-garlic-cheese",
    categoryId: "indpak",
    name: "Naan Garlic Cheese",
    description: "Naan bread with garlic and melted cheese",
    priceEur: 4.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "naan-qeema",
    categoryId: "indpak",
    name: "Naan Qeema",
    description: "Naan bread stuffed with spiced minced meat",
    priceEur: 5.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "chicken-curry",
    categoryId: "indpak",
    name: "Chicken Curry",
    description: "Traditional chicken curry with aromatic spices",
    priceEur: 11.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "chicken-tikka-masala",
    categoryId: "indpak",
    name: "Chicken Tikka Masala",
    description: "Creamy tomato-based curry with chicken tikka",
    priceEur: 12.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "butter-chicken",
    categoryId: "indpak",
    name: "Butter Chicken",
    description: "Creamy butter chicken in rich tomato sauce",
    priceEur: 12.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "chicken-korma",
    categoryId: "indpak",
    name: "Chicken Korma",
    description: "Mild and creamy chicken korma with almonds",
    priceEur: 12.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "chicken-jalfrezi",
    categoryId: "indpak",
    name: "Chicken Jalfrezi",
    description: "Spicy chicken with peppers and onions",
    priceEur: 12.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    spicyLevel: 3,
  },
  {
    id: "beef-curry",
    categoryId: "indpak",
    name: "Beef Curry",
    description: "Slow-cooked beef curry with traditional spices",
    priceEur: 13.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "beef-karahi",
    categoryId: "indpak",
    name: "Beef Karahi",
    description: "Beef cooked in a karahi with tomatoes and spices",
    priceEur: 13.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "lamb-curry",
    categoryId: "indpak",
    name: "Lamb Curry",
    description: "Tender lamb curry with aromatic spices",
    priceEur: 14.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "lamb-rogan-josh",
    categoryId: "indpak",
    name: "Lamb Rogan Josh",
    description: "Kashmiri-style lamb curry in red sauce",
    priceEur: 15.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "vegetable-curry",
    categoryId: "indpak",
    name: "Vegetable Curry",
    description: "Mixed vegetable curry with traditional spices",
    priceEur: 10.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "dal-tadka",
    categoryId: "indpak",
    name: "Dal Tadka",
    description: "Yellow lentils tempered with spices",
    priceEur: 8.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "palak-paneer",
    categoryId: "indpak",
    name: "Palak Paneer",
    description: "Cottage cheese in creamy spinach sauce",
    priceEur: 11.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "chana-masala",
    categoryId: "indpak",
    name: "Chana Masala",
    description: "Spiced chickpea curry",
    priceEur: 9.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
    isVegan: true,
  },

  // ============ NAAN ============
  {
    id: "naan-plain",
    categoryId: "naan",
    name: "Naan Plain",
    description: "Traditional plain naan bread",
    priceEur: 2.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "naan-butter",
    categoryId: "naan",
    name: "Naan Butter",
    description: "Soft naan bread brushed with butter",
    priceEur: 3.0,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "naan-garlic",
    categoryId: "naan",
    name: "Naan Garlic",
    description: "Naan bread with garlic and herbs",
    priceEur: 3.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "naan-cheese",
    categoryId: "naan",
    name: "Naan Cheese",
    description: "Naan bread stuffed with melted cheese",
    priceEur: 4.0,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "naan-garlic-cheese",
    categoryId: "naan",
    name: "Naan Garlic Cheese",
    description: "Naan bread with garlic and melted cheese",
    priceEur: 4.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "naan-qeema",
    categoryId: "naan",
    name: "Naan Qeema",
    description: "Naan bread stuffed with spiced minced meat",
    priceEur: 5.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },

  // ============ CURRIES ============
  {
    id: "chicken-curry",
    categoryId: "curries",
    name: "Chicken Curry",
    description: "Traditional chicken curry with aromatic spices",
    priceEur: 11.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "chicken-tikka-masala",
    categoryId: "curries",
    name: "Chicken Tikka Masala",
    description: "Creamy tomato-based curry with chicken tikka",
    priceEur: 12.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "butter-chicken",
    categoryId: "curries",
    name: "Butter Chicken",
    description: "Creamy butter chicken in rich tomato sauce",
    priceEur: 12.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "chicken-korma",
    categoryId: "curries",
    name: "Chicken Korma",
    description: "Mild and creamy chicken korma with almonds",
    priceEur: 12.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "chicken-jalfrezi",
    categoryId: "curries",
    name: "Chicken Jalfrezi",
    description: "Spicy chicken with peppers and onions",
    priceEur: 12.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    spicyLevel: 3,
  },
  {
    id: "beef-curry",
    categoryId: "curries",
    name: "Beef Curry",
    description: "Slow-cooked beef curry with traditional spices",
    priceEur: 13.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "beef-karahi",
    categoryId: "curries",
    name: "Beef Karahi",
    description: "Beef cooked in a karahi with tomatoes and spices",
    priceEur: 13.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "lamb-curry",
    categoryId: "curries",
    name: "Lamb Curry",
    description: "Tender lamb curry with aromatic spices",
    priceEur: 14.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "lamb-rogan-josh",
    categoryId: "curries",
    name: "Lamb Rogan Josh",
    description: "Kashmiri-style lamb curry in red sauce",
    priceEur: 15.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "vegetable-curry",
    categoryId: "curries",
    name: "Vegetable Curry",
    description: "Mixed vegetable curry with traditional spices",
    priceEur: 10.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "dal-tadka",
    categoryId: "curries",
    name: "Dal Tadka",
    description: "Yellow lentils tempered with spices",
    priceEur: 8.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "palak-paneer",
    categoryId: "curries",
    name: "Palak Paneer",
    description: "Cottage cheese in creamy spinach sauce",
    priceEur: 11.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "chana-masala",
    categoryId: "curries",
    name: "Chana Masala",
    description: "Spiced chickpea curry",
    priceEur: 9.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
    isVegan: true,
  },

  // ============ TANDOORI GRILL ============
  {
    id: "chicken-tikka",
    categoryId: "tandoori",
    name: "Chicken Tikka",
    description: "Marinated chicken pieces cooked in tandoor",
    priceEur: 12.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "malai-boti",
    categoryId: "tandoori",
    name: "Malai Boti",
    description: "Creamy marinated chicken pieces, mild and tender",
    priceEur: 13.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "seekh-kebab",
    categoryId: "tandoori",
    name: "Seekh Kebab",
    description: "Spiced minced meat skewers cooked in tandoor",
    priceEur: 11.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "tandoori-wings",
    categoryId: "tandoori",
    name: "Tandoori Wings",
    description: "Chicken wings marinated and grilled in tandoor",
    priceEur: 9.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "tandoori-leg",
    categoryId: "tandoori",
    name: "Tandoori Leg",
    description: "Whole chicken leg marinated and cooked in tandoor",
    priceEur: 8.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "mix-grill",
    categoryId: "tandoori",
    name: "Mix Grill",
    description: "Assorted tandoori items - tikka, seekh kebab, wings, and more",
    priceEur: 18.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "lamb-chops",
    categoryId: "tandoori",
    name: "Lamb Chops",
    description: "Marinated lamb chops grilled to perfection",
    priceEur: 16.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },

  // ============ RICE ============
  {
    id: "white-rice",
    categoryId: "rice",
    name: "White Rice",
    description: "Plain steamed basmati rice",
    priceEur: 3.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "jeera-rice",
    categoryId: "rice",
    name: "Jeera Rice",
    description: "Basmati rice tempered with cumin seeds",
    priceEur: 4.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "kesar-rice",
    categoryId: "rice",
    name: "Kesar Rice",
    description: "Fragrant saffron rice",
    priceEur: 5.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "rice-platter",
    categoryId: "rice",
    name: "Rice Platter",
    description: "Rice served with curry of your choice",
    priceEur: 13.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },

  // ============ SNACKS ============
  {
    id: "samosa-2pz",
    categoryId: "snacks",
    name: "Samosa 2pz",
    description: "Crispy pastry filled with spiced potatoes and peas",
    priceEur: 4.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "onion-bhaji",
    categoryId: "snacks",
    name: "Onion Bhaji",
    description: "Crispy onion fritters",
    priceEur: 5.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "mozzarella-sticks",
    categoryId: "snacks",
    name: "Mozzarella Sticks",
    description: "Crispy mozzarella sticks with marinara sauce",
    priceEur: 5.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "jalapeno-poppers",
    categoryId: "snacks",
    name: "Jalapeño Poppers",
    description: "Spicy jalapeños stuffed with cream cheese",
    priceEur: 5.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
    spicyLevel: 2,
  },
  {
    id: "onion-rings",
    categoryId: "snacks",
    name: "Onion Rings",
    description: "Crispy golden onion rings",
    priceEur: 4.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "patatine-fritte",
    categoryId: "snacks",
    name: "Patatine Fritte",
    description: "Classic french fries",
    priceEur: 3.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: "loaded-fries",
    categoryId: "snacks",
    name: "Loaded Fries",
    description: "Fries topped with cheese, chicken, and special sauce",
    priceEur: 7.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },

  // ============ FAMILY DEALS ============
  {
    id: "family-burger-deal",
    categoryId: "family",
    name: "Family Burger Deal",
    description: "4 burgers, 4 drinks, large fries - perfect for the family",
    priceEur: 39.99,
    imageUrl: "/family-burger-meal-deal--professional-food-photogr.jpg",
    available: true,
    published: true,
  },
  {
    id: "family-chicken-deal",
    categoryId: "family",
    name: "Family Chicken Deal",
    description: "8 pieces chicken, 4 drinks, 2 large fries",
    priceEur: 42.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "family-mix-grill-deal",
    categoryId: "family",
    name: "Family Mix Grill",
    description: "Mixed grill platter for 4 people with naan and rice",
    priceEur: 54.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "family-curry-deal",
    categoryId: "family",
    name: "Family Curry Deal",
    description: "2 curries, rice, 4 naan, and 4 drinks",
    priceEur: 49.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },

  // ============ DESSERTS ============
  {
    id: "gulab-jamun",
    categoryId: "desserts",
    name: "Gulab Jamun",
    description: "Sweet milk dumplings in rose syrup",
    priceEur: 4.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "baklava",
    categoryId: "desserts",
    name: "Baklava",
    description: "Layered pastry with nuts and honey",
    priceEur: 4.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "souffle-cioccolato",
    categoryId: "desserts",
    name: "Soufflé al Cioccolato",
    description: "Warm chocolate soufflé with ice cream",
    priceEur: 5.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "kheer",
    categoryId: "desserts",
    name: "Kheer",
    description: "Traditional rice pudding with cardamom and nuts",
    priceEur: 4.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "kulfi",
    categoryId: "desserts",
    name: "Kulfi",
    description: "Traditional Indian ice cream",
    priceEur: 3.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "tiramisu",
    categoryId: "desserts",
    name: "Tiramisu",
    description: "Classic Italian tiramisu",
    priceEur: 5.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },

  // ============ BEVANDE ============
  {
    id: "coca-cola",
    categoryId: "bevande",
    name: "Coca Cola",
    description: "330ml can",
    priceEur: 2.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "coca-cola-zero",
    categoryId: "bevande",
    name: "Coca Cola Zero",
    description: "330ml can",
    priceEur: 2.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "fanta",
    categoryId: "bevande",
    name: "Fanta",
    description: "330ml can",
    priceEur: 2.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "sprite",
    categoryId: "bevande",
    name: "Sprite",
    description: "330ml can",
    priceEur: 2.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "acqua-naturale",
    categoryId: "bevande",
    name: "Acqua Naturale 50cl",
    description: "Still water",
    priceEur: 1.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "acqua-frizzante",
    categoryId: "bevande",
    name: "Acqua Frizzante 50cl",
    description: "Sparkling water",
    priceEur: 1.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "the-limone",
    categoryId: "bevande",
    name: "Thè Limone",
    description: "Lemon iced tea",
    priceEur: 2.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "the-pesca",
    categoryId: "bevande",
    name: "Thè Pesca",
    description: "Peach iced tea",
    priceEur: 2.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
  {
    id: "mango-lassi",
    categoryId: "bevande",
    name: "Mango Lassi",
    description: "Traditional yogurt drink with mango",
    priceEur: 3.99,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "sweet-lassi",
    categoryId: "bevande",
    name: "Sweet Lassi",
    description: "Traditional sweet yogurt drink",
    priceEur: 3.5,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
    isVegetarian: true,
  },
  {
    id: "coca-cola-1l",
    categoryId: "bevande",
    name: "Coca Cola 1L",
    description: "1 liter bottle",
    priceEur: 4.0,
    imageUrl: "/placeholder.svg?height=400&width=400",
    available: true,
    published: true,
  },
]

export function getMenuItemsByCategory(categoryId: string): MenuItem[] {
  return menuItems.filter((item) => item.categoryId === categoryId && item.published !== false)
}

export function getMenuItemById(id: string): MenuItem | undefined {
  return menuItems.find((item) => item.id === id)
}

export function getCategoryById(id: string): MenuCategory | undefined {
  return menuCategories.find((cat) => cat.id === id)
}
